### ISSUE TITLE
Automatically download latest release

### ISSUE THREAD

**Issue by ThomDietrich** [yann25/Sonoff-Tasmota_autoflash#3]
One great addition would be to download the latest Sonoff-Tasmota release automatically.

You can find the latest release be prarsing this json document: https://api.github.com/repos/arendst/Sonoff-Tasmota/releases
You are looking for the "browser_download_url" below the first asset. You can additionally retrieve the "size" for comparison and a simple download verification. You could additionally print tag name and body for clarity.

**Comment by yann25** [comment]
I have a working programm, but I was wondering where to save it. For know I save it in the same directory the python script is in. It's probably not the proper way is it?

**Comment by ThomDietrich** [comment]
Good question. Either you go with a temporary file or you store the file in memory and spare yourself the filesystem fiddling, I've no ready to go solution for the second but a temporary file is easy:
https://docs.python.org/2.7/library/tempfile.html

**Comment by yann25** [comment]
Thank you I think I will use a temp folder. I just read my question again. Good that you understood me. "It" meant the .bin file not the python file. :smile:

**Comment by ThomDietrich** [comment]
Out of interest, why didn't you use tempfile instead of tempdir+"firmware.bin"?
Also instead of "/" or "\" you can use `os.sep` ;)

**Comment by yann25** [comment]
It was a kind of workaround because I could not find a way to create a temp file from the urllib object 😄 I'm really not fluent in python or programming at all, but I will try it if you say it should work 🙈

**Comment by ThomDietrich** [comment]
I'm not saying it should work! I would expect that but in the end it's something one needs to test out. I'm just pitching ideas ;)

**Comment by yann25** [comment]
I will look at it again :D feels good to have a goal when programming something, better than doing some exercise from a workbook. 

esptools required a path to the file, so in the end I would have to get the filepath from tempfile which is kind of the same only that it will be cleaned up automatically in the end.

**Comment by ThomDietrich** [comment]
That's exactly what I tell students in my engineering class 😄

Maybe this will be helpful?https://gist.github.com/sligodave/6539531

**Comment by yann25** [comment]
With all the help you give me you could have almost done it yourself :smile:

**Comment by ThomDietrich** [comment]
Where would be the fun in that? Haha
It's great to work on projects together, unrelated to how small they are. If we have a working flash tool in the end and you learned something new by doing so, everything is great.

**Comment by yann25** [comment]
There is a lot to learn especially how to handle the code on github and on my PC. Do you use Eclipse or something like that? Any hints how to cope with that?

I have a testfile working with tempfile seemed like I was to lazy to find a good way and just worked around ... 🙈

**Comment by ThomDietrich** [comment]
Eclipse is a solid choice. You can use the integrated git client but for better control (especially for a newcomer) I'd recommend GitKraken. After you've gained some experience and if you are looking for a more powerful solution, SmartGit is my daily driver.
Glad the tempfile idea is working. Sometimes it takes multiple steps. Happens to me too all the time.
