### ISSUE TITLE
pip package setup

### ISSUE THREAD

**Issue by ThomDietrich** [yann25/Sonoff-Tasmota_autoflash#4]
You are installing a module via pip from inside your script (unconditionally) While there is no real harm in it, the better way would be to make your own program installable and define "esptool" as a dependency.

http://peterdowns.com/posts/first-time-with-pypi.html

You can "pip install" a module directly from github but uploading to PyPI is the easier option.

**Comment by yann25** [comment]
I tried your link, but apparently distutils can not add dependencies so I used setuptools. It should work now. 
Maybe someone/you can try it and if it works I can close the issue 😄

**Comment by ThomDietrich** [comment]
I'm sorry, I've posted the first google result to point you in a direction. Setuptools is the way to go! Probably the better link would have been: https://packaging.python.org/distributing/

Did you already upload to PyPI?

I'll not be able to test with real hardware before Saturday. Stay tuned ;)

**Comment by yann25** [comment]
Yes the latest release should be uploaded
