### ISSUE TITLE
Stand alone application

### ISSUE THREAD

**Issue by ThomDietrich** [yann25/Sonoff-Tasmota_autoflash#7]
This script is a nice help but does not yet solve the original intention: Making the flashing process easier. Instead of PlatformIO a user now needs to install python+pip+dependencies...

I have no experience with http://www.pyinstaller.org but it's widely recommended as a wrapper for python programs. Maybe it would be worth tinkering around with.

**Comment by yann25** [comment]
I just tried it. All good on a Linux based system. Had problems on Windows due to unicodedecodeerror.

Process is very easy:
- install PyInstaller with pip
- run the command: PyInstaller --onefile filepathyouwanttowrap

That's all.

Where would you publish it? Also here?

**Comment by ThomDietrich** [comment]
sounds great. Sadly I suspect most end users to work with Windows.
just under releases yes 👍

**Comment by yann25** [comment]
I am not really sure if it is a problem, but PyInstaller runs the file looks what is needed an makes a package. So maybe if one has not esptools installed it will not work because it handled as console command. 
I did not think of this when I was testing, so maybe it only worked because I had esptools already installed.

I will look at it again tomorrow.

**Comment by yann25** [comment]
As I was thinking... as soon as I uninstall esptool I get the error that the command esptool.py is not known

**Comment by ThomDietrich** [comment]
Yeah sure but that's one common requirement. See here:
https://pythonhosted.org/PyInstaller/operating-mode.html#analysis-finding-the-files-your-program-needs
https://pythonhosted.org/PyInstaller/spec-files.html

**Comment by ThomDietrich** [comment]
Also look what I found: https://github.com/marcelstoer/nodemcu-pyflasher

**Comment by yann25** [comment]
Thank you I will look at it 😄

**Comment by yann25** [comment]
Standalone versions can and will be added to the next release
